# Generated by Django 4.2.8 on 2024-01-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DailyDiary1', '0003_hawa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hawa',
        ),
    ]
